N = 4, seed = 279, tester = IP Gen Col IP
Traceback (most recent call last):
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\parallel_solve.py", line 27, in <module>
    answer = solver.solve(timeout=timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\ttp_master.py", line 314, in solve
    integer_patterns, integer_solution = self.integer_solver(timeout=timeout)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\ttp_master.py", line 352, in integer_solver
    + quicksum(self.x_int[i] for i in self.away_t_s[t, s]) == 1),
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src\gurobipy\gurobi.pxi", line 3706, in gurobipy.quicksum
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\ttp_master.py", line 352, in <genexpr>
    + quicksum(self.x_int[i] for i in self.away_t_s[t, s]) == 1),
               ~~~~~~~~~~^^^
IndexError: list index out of range


N = 4, seed = 433, tester = IP Gen Col IP
Traceback (most recent call last):
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\parallel_solve.py", line 27, in <module>
    answer = solver.solve(timeout=timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\ttp_master.py", line 314, in solve
    integer_patterns, integer_solution = self.integer_solver(timeout=timeout)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\ttp_master.py", line 351, in integer_solver
    (quicksum(self.x_int[i] for i in self.home_t_s[t, s]) 
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src\gurobipy\gurobi.pxi", line 3706, in gurobipy.quicksum
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\ttp_master.py", line 351, in <genexpr>
    (quicksum(self.x_int[i] for i in self.home_t_s[t, s]) 
              ~~~~~~~~~~^^^
IndexError: list index out of range


N = 4, seed = 547, tester = IP Gen Col IP
Traceback (most recent call last):
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\parallel_solve.py", line 27, in <module>
    answer = solver.solve(timeout=timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\ttp_master.py", line 314, in solve
    integer_patterns, integer_solution = self.integer_solver(timeout=timeout)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\ttp_master.py", line 351, in integer_solver
    (quicksum(self.x_int[i] for i in self.home_t_s[t, s]) 
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src\gurobipy\gurobi.pxi", line 3706, in gurobipy.quicksum
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\ttp_master.py", line 351, in <genexpr>
    (quicksum(self.x_int[i] for i in self.home_t_s[t, s]) 
              ~~~~~~~~~~^^^
IndexError: list index out of range


N = 4, seed = 910, tester = IP Gen Col IP
Traceback (most recent call last):
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\parallel_solve.py", line 27, in <module>
    answer = solver.solve(timeout=timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\ttp_master.py", line 314, in solve
    integer_patterns, integer_solution = self.integer_solver(timeout=timeout)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\ttp_master.py", line 351, in integer_solver
    (quicksum(self.x_int[i] for i in self.home_t_s[t, s]) 
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src\gurobipy\gurobi.pxi", line 3706, in gurobipy.quicksum
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\ttp_master.py", line 351, in <genexpr>
    (quicksum(self.x_int[i] for i in self.home_t_s[t, s]) 
              ~~~~~~~~~~^^^
IndexError: list index out of range


N = 4, seed = 937, tester = IP Gen Col IP
Traceback (most recent call last):
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\parallel_solve.py", line 27, in <module>
    answer = solver.solve(timeout=timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\ttp_master.py", line 314, in solve
    integer_patterns, integer_solution = self.integer_solver(timeout=timeout)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\ttp_master.py", line 351, in integer_solver
    (quicksum(self.x_int[i] for i in self.home_t_s[t, s]) 
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src\gurobipy\gurobi.pxi", line 3706, in gurobipy.quicksum
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\ttp_master.py", line 351, in <genexpr>
    (quicksum(self.x_int[i] for i in self.home_t_s[t, s]) 
              ~~~~~~~~~~^^^
IndexError: list index out of range


N = 6, seed = 306, tester = IP Gen Col IP
Traceback (most recent call last):
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\parallel_solve.py", line 27, in <module>
    answer = solver.solve(timeout=timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\ttp_master.py", line 314, in solve
    integer_patterns, integer_solution = self.integer_solver(timeout=timeout)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\ttp_master.py", line 351, in integer_solver
    (quicksum(self.x_int[i] for i in self.home_t_s[t, s]) 
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src\gurobipy\gurobi.pxi", line 3706, in gurobipy.quicksum
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\ttp_master.py", line 351, in <genexpr>
    (quicksum(self.x_int[i] for i in self.home_t_s[t, s]) 
              ~~~~~~~~~~^^^
IndexError: list index out of range


N = 6, seed = 690, tester = IP Gen Col IP
Traceback (most recent call last):
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\parallel_solve.py", line 27, in <module>
    answer = solver.solve(timeout=timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\ttp_master.py", line 314, in solve
    integer_patterns, integer_solution = self.integer_solver(timeout=timeout)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\ttp_master.py", line 365, in integer_solver
    quicksum(self.x_int[i] * self.costs[i] for i in range(len(self.patterns)))
  File "src\gurobipy\gurobi.pxi", line 3706, in gurobipy.quicksum
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\ttp_master.py", line 365, in <genexpr>
    quicksum(self.x_int[i] * self.costs[i] for i in range(len(self.patterns)))
             ~~~~~~~~~~^^^
IndexError: list index out of range


N = 6, seed = 89, tester = IP Gen Col IP
Traceback (most recent call last):
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\parallel_solve.py", line 27, in <module>
    answer = solver.solve(timeout=timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\ttp_master.py", line 314, in solve
    integer_patterns, integer_solution = self.integer_solver(timeout=timeout)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\ttp_master.py", line 365, in integer_solver
    quicksum(self.x_int[i] * self.costs[i] for i in range(len(self.patterns)))
  File "src\gurobipy\gurobi.pxi", line 3706, in gurobipy.quicksum
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\ttp_master.py", line 365, in <genexpr>
    quicksum(self.x_int[i] * self.costs[i] for i in range(len(self.patterns)))
             ~~~~~~~~~~^^^
IndexError: list index out of range


N = 8, seed = 335, tester = IP Gen Col IP
Traceback (most recent call last):
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\parallel_solve.py", line 27, in <module>
    answer = solver.solve(timeout=timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\ttp_master.py", line 314, in solve
    integer_patterns, integer_solution = self.integer_solver(timeout=timeout)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\ttp_master.py", line 365, in integer_solver
    quicksum(self.x_int[i] * self.costs[i] for i in range(len(self.patterns)))
  File "src\gurobipy\gurobi.pxi", line 3706, in gurobipy.quicksum
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\ttp_master.py", line 365, in <genexpr>
    quicksum(self.x_int[i] * self.costs[i] for i in range(len(self.patterns)))
             ~~~~~~~~~~^^^
IndexError: list index out of range


N = 8, seed = 55, tester = IP Gen Col IP
Traceback (most recent call last):
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\parallel_solve.py", line 27, in <module>
    answer = solver.solve(timeout=timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\ttp_master.py", line 314, in solve
    integer_patterns, integer_solution = self.integer_solver(timeout=timeout)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\ttp_master.py", line 365, in integer_solver
    quicksum(self.x_int[i] * self.costs[i] for i in range(len(self.patterns)))
  File "src\gurobipy\gurobi.pxi", line 3706, in gurobipy.quicksum
  File "C:\Users\Roberto B\Documents\A Universidad\VIII Semestre\Ipre\TTP-Study\ttp_master.py", line 365, in <genexpr>
    quicksum(self.x_int[i] * self.costs[i] for i in range(len(self.patterns)))
             ~~~~~~~~~~^^^
IndexError: list index out of range


